import Head from 'next/head';

const Header = ({title = 'Keaki Online Marketplace'}) => {
  return (
    <Head>
      <title>{title}</title>
      {/* <meta name="description" content="Generated by create next app" /> */}
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Header;
